"""Added post image cascade

Revision ID: 388901ae3ce3
Revises: 8b1a4ee5f873
Create Date: 2025-03-06 19:41:29.706929

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# Revision identifiers, used by Alembic
revision = '388901ae3ce3'
down_revision = '8b1a4ee5f873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute('INSERT INTO post_images_new (id, post_id, image_url, created_at, updated_at) SELECT id, post_id, image_url, created_at, updated_at FROM post_images')

    op.drop_table('post_images')

    op.rename_table('post_images_new', 'post_images')

    if environment == "production":
        op.execute(f"ALTER TABLE post_images SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images_old',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute('INSERT INTO post_images_old (id, post_id, image_url, created_at, updated_at) SELECT id, post_id, image_url, created_at, updated_at FROM post_images')

    op.drop_table('post_images')

    op.rename_table('post_images_old', 'post_images')
